# Docs for the Fly.io deployment: https://fly.io/docs/getting-started/github-actions/
# More GitHub Actions for Fly.io: https://github.com/fly-apps/actions

name: Build and deploy Dockerized app to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: cd backend && mvn clean install

      # Create a Dockerfile in the /backend directory
      - name: Create Dockerfile
        run: echo "FROM openjdk:17\nWORKDIR /app\nCOPY backend/target/your-app-name.jar /app/\nEXPOSE 8080\nCMD [\"java\", \"-jar\", \"your-app-name.jar\"]" > backend/Dockerfile

      - name: Dockerize the JAR app
        run: docker build -t gwave backend/

      - name: Log in to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Install Flyctl CLI
        run: |
          curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
