name: Build and deploy Dockerized app to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: cd backend && mvn clean install

      # Create a Dockerfile in the /backend directory with LF line terminators
      - name: Create Dockerfile
        run: |
          echo -e "FROM openjdk:17\nWORKDIR /app\nCOPY target/greenwave-0.0.1-SNAPSHOT.jar /app/\nEXPOSE 8080\nCMD [\"java\", \"-jar\", \"greenwave-0.0.1-SNAPSHOT.jar\"]" > backend/Dockerfile
      - name: Dockerize the JAR app 
        run: cd backend && docker build -t gwave .
        
        
      - name: Install Flyctl CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
#       - name: Create to Fly.io
#         run: flyctl launch --remote-only --name gwave -i backend/ -r arn
#         env:
#             FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Create to Fly.io
        run: flyctl deploy --remote-only -a gwave
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        
